package de.konqi.roborockbridge.roborockbridge.protocol.dto.homedetail

data class Device(
    val duid: String,
    val name: String,
    val attribute: Any?,
    val activeTime: Long,
    val localKey: String,
    val runtimeEnv: Any?,
    val timeZoneId: String,
    val iconUrl: String,
    val productId: String,
    val lon: Any?,
    val lat: Any?,
    val share: Boolean,
    val shareTime: Any?,
    val online: Boolean,
    val fv: String,
    val pv: String,
    val roomId: Any?,
    val tuyaUuid: Any?,
    val tuyaMigrated: Boolean,
    val extra: Any?,
    val setting: Any?,
    val sn: String,
    val featureSet: String,
    val newFeatureSet: String,
    val deviceStatus: DeviceStatus,
    val silentOtaSwitch: Boolean,
    val f: Boolean,
)