name: prepare gradle
description: prepare for build with gradle
outputs:
  artifact-version:
    description: version stripped of the -SNAPSHOT part
    value: ${{ steps.version_step.outputs.artifact_version }}
  gradle-version-property:
    description: version as defined in gradle file
    value: ${{ steps.version_step.outputs.gradle_version_property }}
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Extract version
      id: version_step
      shell: bash
      run: |
        export GRADLE_VERSION_PROPERTY=`./gradlew properties -q | awk '/^version:/ {print $2}'`
        echo gradle_version_property=$GRADLE_VERSION_PROPERTY >> $GITHUB_OUTPUT
        export ARTIFACT_VERSION=`cut -d'-' -f1 <<<"$GRADLE_VERSION_PROPERTY"`
        echo artifact_version=$ARTIFACT_VERSION >> $GITHUB_OUTPUT
