name: Build Gradle project

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: prepare
        id: prepare
        uses: ./.github/actions/prepare
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Check for new version
        uses: ./.github/actions/detect-new-version
        with:
          token: ${{ secrets.PAT }}
          version: v${{ steps.prepare.outputs.artifact-version }}
