name: Release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: prepare
        id: prepare
        uses: ./.github/actions/prepare
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*${{ steps.prepare.outputs.gradle_version_property }}.jar,build/resources/main/application.yaml"
          draft: true
